# Generated by Django 4.2.2 on 2023-07-06 23:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='UserComment',
        ),
        migrations.RenameField(
            model_name='usercomment',
            old_name='timestamp',
            new_name='time',
        ),
    ]
